### ISSUE TITLE
Achievement testartilleryman bug?

### ISSUE THREAD

**Issue by Blcz** [Phalynx/WoT-Dossier-Cache-to-JSON#17]
Hi Phalynx, the new achievement *testartilleryman* seems to return absolutely random numbers. Which implies that it could be wrongly defined in structure file. Or maybe it is future achievement, missing in dossier as yet. Can you take a look at this, thanks.

**Comment by Blcz** [comment]
I am looking at it now. Seems like this testartilleryman should not be in structures at all. It is defined with offset 159, yet whole achievement block is 159 length so we read data after the block. The length 159 didn't change between dossier versions 88 and 89 (testartilleryman was introduced into structures 89) and is the same even now in version 92.

Can you confirm it? Thanks.

**Comment by Phalynx** [comment]
testartilleryman is still listed in records.py as position 599, that's why structures.json is listing this.
It has also an official translation as "Rocket Scientist" in achievements.mo.

Beside this, I have 2851 battles with this achievement - source are Battle Results.
Looking at dossiers, I have ~316k dossiers with this achievement, but with very high values. 

Very suspicious. I would keep this open and dig on this later.

**Comment by Blcz** [comment]
Well if it is Rocket Scientist, then i am pretty sure, that it belongs to the player account, but not to the (every) tank. I have gained it too, it was 1st. April achievement. :)
